-- DB user
DROP USER IF EXISTS 'cmsc198user';
CREATE USER 'cmsc198user' IDENTIFIED BY 'ZNBhSKChnoTds';

-- APPLICATION DATABASE
DROP DATABASE IF EXISTS cmsc198db;
CREATE DATABASE cmsc198db;

-- GRANTS ALL PRIVILEGE ON APPLICATION DATABASE TO DB USER
GRANT ALL ON cmsc198db.* TO 'cmsc198user'@'localhost';
FLUSH PRIVILEGES;

USE cmsc198db;

-- 'OFFICE' Table
DROP TABLE IF EXISTS office;
CREATE TABLE office(
	officeID INT NOT NULL AUTO_INCREMENT,
	officeAbbr VARCHAR(128) NOT NULL,
	officeName VARCHAR(128) NOT NULL,
	officeEmail VARCHAR(128) NOT NULL,
	telephoneNumber INT NOT NULL,
	faxNumber INT NOT NULL,
	voip INT NOT NULL,
	parentUnit INT NOT NULL,
	officeType VARCHAR(128) NOT NULL,
	favorite INT NOT NULL DEFAULT '0',
	priority INT NOT NULL DEFAULT '5',
	dateCreated DATE DEFAULT NULL,
	createdBy INT DEFAULT NULL,
	active INT NOT NULL DEFAULT '1',
	head VARCHAR(128) NOT NULL,
	PRIMARY KEY(officeID)
);

-- 'CLIENT' Table
DROP TABLE IF EXISTS client;
CREATE TABLE client(
	clientID INT NOT NULL AUTO_INCREMENT,
    username VARCHAR(32) NOT NULL UNIQUE,
    password VARCHAR(256) NOT NULL,
    givenName VARCHAR(64) NOT NULL,
    lastName VARCHAR(64) NOT NULL,
    designation VARCHAR(20) NOT NULL,
    officeId INT NOT NULL,
    dateCreated DATE DEFAULT NULL,
	createdBy INT DEFAULT NULL,
	active INT NOT NULL DEFAULT '1',
    FOREIGN KEY(officeId) REFERENCES office(officeID),
    PRIMARY KEY(clientID)
);

-- 'ADMINACC' Table
DROP TABLE IF EXISTS adminAcc;
CREATE TABLE adminAcc(
	adminID INT NOT NULL AUTO_INCREMENT,
    username VARCHAR(32) NOT NULL UNIQUE,
    password VARCHAR(256) NOT NULL,
    givenName VARCHAR(64) NOT NULL,
    lastName VARCHAR(64) NOT NULL,
    isTechnician INT NOT NULL,
    dateCreated DATE DEFAULT NULL,
	createdBy INT DEFAULT NULL,
	active INT NOT NULL DEFAULT '1',
    PRIMARY KEY(adminID)
);

-- 'SUPERADMIN' Table
DROP TABLE IF EXISTS superAdmin;
CREATE TABLE superAdmin(
	superAdminID INT NOT NULL AUTO_INCREMENT,
    username VARCHAR(32) NOT NULL UNIQUE,
    password VARCHAR(256) NOT NULL,
    givenName VARCHAR(64) NOT NULL,
    lastName VARCHAR(64) NOT NULL,
    dateCreated DATE DEFAULT NULL,
	createdBy INT DEFAULT NULL,
	active INT NOT NULL DEFAULT '1',
    PRIMARY KEY(superAdminID)
);

-- 'JOB' Table
DROP TABLE IF EXISTS job;
CREATE TABLE job(
	jobID INT NOT NULL AUTO_INCREMENT,
	startDate TIMESTAMP,
	finishDate TIMESTAMP NULL,
	jobStatus VARCHAR(10) DEFAULT 'PENDING',
	clientID INT NOT NULL,
	adminID INT NULL,
	dateCreated DATE DEFAULT NULL,
	createdBy INT DEFAULT NULL,
	active INT NOT NULL DEFAULT '1',
	FOREIGN KEY(clientID) REFERENCES client(clientID),
	FOREIGN KEY(adminID) REFERENCES adminAcc(adminID),
	PRIMARY KEY(jobID)
);

-- 'MATERIALS' Table
DROP TABLE IF EXISTS materials;
CREATE TABLE materials(
	materialID INT NOT NULL AUTO_INCREMENT,
	materialName VARCHAR(32) NOT NULL,
	materialDescription VARCHAR(256) NOT NULL,
	materialCost INT NOT NULL,
	jobId INT NOT NULL,
	dateCreated DATE DEFAULT NULL,
	createdBy INT DEFAULT NULL,
	active INT NOT NULL DEFAULT '1',
	FOREIGN KEY(jobId) REFERENCES job(jobID), 
	PRIMARY KEY(materialID)
);